### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by sicao1** [sicao1/Project_1_The_Game#1]
```[tasklist]
### My tasks
- [ ] create a title logo
- [ ] find font in Mortal Kombat Style - "Choose your fighter". if possible make it flashing\

Javascript
- [ ] make it so character img enlarges into part 2 - character selection hover vs. clicked
- [ ] player 1 choices first
- [ ] the player 2
